package com.example.app_data_mujer

data class QuizQuestion(
    val category: String,
    val question: String,
    val options: List<String>,
    val correctOptionIndex: Int
)

val EasyQuestionsList = listOf(
    QuizQuestion("Matemáticas", "¿En qué área destacó Sophie Germain?", listOf("Medicina", "Matemáticas", "Astronomía", "Biología"), 1),
    QuizQuestion("Matemáticas", "¿Qué científica es conocida por los “primos de Sophie Germain”?", listOf("Emmy Noether", "Sophie Germain", "Maryam Mirzakhani", "Ada Lovelace"), 1),
    QuizQuestion("Matemáticas", "¿Qué científica ganó la Medalla Fields en Matemáticas?", listOf("Maryam Mirzakhani", "Marie Curie", "Grace Hopper", "Caroline Herschel"), 0),
    QuizQuestion("Astronomía", "¿Qué científica descubrió ocho cometas?", listOf("Maria Mitchell", "Caroline Herschel", "Nancy Grace Roman", "Henrietta Leavitt"), 1),
    QuizQuestion("Astronomía", "¿Quién descubrió la relación entre el período y la luminosidad de las estrellas Cefeidas?", listOf("Annie Jump Cannon", "Henrietta Swan Leavitt", "Caroline Herschel", "Maria Mitchell"), 1),
    QuizQuestion("Astronomía", "¿Qué astrónoma creó el sistema de clasificación estelar OBAFGKM?", listOf("Nancy Grace Roman", "Maria Mitchell", "Annie Jump Cannon", "Caroline Herschel"), 2),
    QuizQuestion("Astronomía", "¿Quién es conocida como la “madre del telescopio espacial Hubble”?", listOf("Nancy Grace Roman", "Rosalind Franklin", "Donna Strickland", "Ada Lovelace"), 0),
    QuizQuestion("Computación", "¿Qué científica es considerada una pionera de la programación?", listOf("Marie Curie", "Ada Lovelace", "Patricia Bath", "Barbara McClintock"), 1),
    QuizQuestion("Computación", "¿Para qué máquina escribió Ada Lovelace un algoritmo?", listOf("La máquina analítica", "El telescopio Hubble", "El microscopio electrónico", "La computadora ENIAC"), 0),
    QuizQuestion("Computación", "¿Qué científica desarrolló uno de los primeros compiladores?", listOf("Grace Murray Hopper", "Jude Milhon", "Evelyn Berezin", "Lynn Conway"), 0),
    QuizQuestion("Computación", "¿Con qué lenguaje de programación se relaciona especialmente Grace Hopper?", listOf("Kotlin", "COBOL", "Python", "Java"), 1),
    QuizQuestion("Computación", "¿Qué científica creó un sistema temprano de procesamiento de textos llamado Data Secretary?", listOf("Ada Lovelace", "Evelyn Berezin", "Hedy Lamarr", "Lynn Conway"), 1),
    QuizQuestion("Ingeniería", "¿Qué científica inventó el Kevlar?", listOf("Stephanie Kwolek", "Rosalind Franklin", "Marie Curie", "Irène Joliot-Curie"), 0),
    QuizQuestion("Física", "¿Qué científica trabajó junto a Pierre Curie y estudió la radiactividad?", listOf("Lise Meitner", "Marie Curie", "Ada Yonath", "Rosalyn Yalow"), 1),
    QuizQuestion("Física", "¿Qué científica fue hija de Marie y Pierre Curie?", listOf("Irène Joliot-Curie", "Rosalind Franklin", "Margarita Salas", "Lise Meitner"), 0),
    QuizQuestion("Física", "¿Qué descubrieron Irène Joliot-Curie y Frédéric Joliot-Curie?", listOf("La penicilina", "La radiactividad artificial", "El ADN", "Los agujeros negros"), 1),
    QuizQuestion("Química", "¿Qué científica ayudó a documentar e ilustrar los experimentos de Antoine Lavoisier?", listOf("Marie-Anne Paulze-Lavoisier", "Marie Curie", "Stephanie Kwolek", "Ada Yonath"), 0),
    QuizQuestion("Ingeniería", "¿Qué ingeniera solucionó un problema de los motores Rolls-Royce Merlin durante la Segunda Guerra Mundial?", listOf("Emily Warren Roebling", "Edith Clarke", "Beatrice Shilling", "Elisa Leonida Zamfirescu"), 2),
    QuizQuestion("Astronomía", "¿Qué científica fue cantante antes de dedicarse a la astronomía?", listOf("Caroline Herschel", "Maria Mitchell", "Nancy Grace Roman", "Annie Jump Cannon"), 0),
    QuizQuestion("Astronomía", "¿Qué científica descubrió el cometa conocido como “Miss Mitchell's Comet”?", listOf("Caroline Herschel", "Maria Mitchell", "Henrietta Leavitt", "Annie Jump Cannon"), 1)
)

val MediumQuestionsList = listOf(
    QuizQuestion("Matemáticas", "¿Qué ocurrió con Sophie Germain debido a las restricciones educativas para las mujeres de su época?", listOf("Tuvo que estudiar principalmente de forma autodidacta", "Abandonó completamente las matemáticas", "Solo pudo estudiar medicina", "Fue expulsada de la Academia de Ciencias"), 0),
    QuizQuestion("Matemáticas", "¿Qué combinación de áreas conecta especialmente el trabajo de Maryam Mirzakhani?", listOf("Química, medicina y biología", "Geometría, topología y dinámica", "Astronomía, física y química", "Computación, medicina y genética"), 1),
    QuizQuestion("Matemáticas", "¿Qué reconocimiento recibió Sun-Yung Alice Chang en 2015?", listOf("Premio Nobel de Física", "Medalla Fields", "Premio Ruth Lyttle Satter", "Medalla Kelvin"), 2),
    QuizQuestion("Física", "¿Qué proceso físico ayudó Lise Meitner a interpretar junto con Otto Frisch?", listOf("La fusión de estrellas", "La fisión nuclear", "La fotosíntesis", "La superconductividad"), 1),
    QuizQuestion("Física", "¿Por qué Lise Meitner tuvo que abandonar Alemania en 1938?", listOf("Por una expedición científica", "Por persecución nazi debido a su ascendencia judía", "Para trabajar en la NASA", "Para recibir un Premio Nobel"), 1),
    QuizQuestion("Computación", "¿Qué computadora utilizó Mary Tsingou para realizar parte de su trabajo científico?", listOf("ENIAC", "MANIAC", "Colossus", "Harvard Mark I"), 1),
    QuizQuestion("Computación", "¿Qué tipo de sistemas ayudó a estudiar el experimento programado por Mary Tsingou?", listOf("Sistemas no lineales", "Sistemas respiratorios", "Sistemas planetarios", "Sistemas genéticos"), 0),
    QuizQuestion("Física", "¿Qué técnica desarrollada por Donna Strickland permite generar pulsos láser muy intensos?", listOf("RIA", "CPA", "PCR", "OBAFGKM"), 1),
    QuizQuestion("Física", "¿En cuál de estas aplicaciones puede utilizarse la tecnología desarrollada por Donna Strickland?", listOf("Cirugía ocular", "Clasificación de especies", "Producción de vacunas", "Observación de cometas"), 0),
    QuizQuestion("Física", "¿Qué proceso estudia Helen Czerski para comprender mejor la relación entre los océanos y el clima?", listOf("El intercambio de gases entre océano y atmósfera", "La división de células animales", "La formación de planetas", "La radiactividad artificial"), 0),
    QuizQuestion("Ingeniería", "¿Qué institución reconoció a Stephanie Kwolek al incorporarla a su salón de la fama en 1995?", listOf("NASA", "National Inventors Hall of Fame", "Royal Astronomical Society", "Academia de Ciencias de París"), 1),
    QuizQuestion("Química", "¿Cuál fue una función importante de Marie-Anne Paulze-Lavoisier dentro del laboratorio?", listOf("Diseñar cohetes", "Traducir, ilustrar y documentar experimentos", "Construir telescopios", "Programar computadoras"), 1),
    QuizQuestion("Física", "¿Qué utilidad tuvieron los radioisótopos producidos gracias al descubrimiento de Irène Joliot-Curie?", listOf("Solo sirvieron para astronomía", "Tuvieron aplicaciones en medicina, investigación e industria", "Únicamente se utilizaron en matemáticas", "Permitieron crear computadoras"), 1),
    QuizQuestion("Biología", "¿Qué característica del ADN estudió Rosalind Franklin mediante técnicas experimentales?", listOf("Su estructura molecular", "Su capacidad para producir energía", "Su movimiento dentro de la sangre", "Su relación con las estrellas"), 0),
    QuizQuestion("Biología", "¿Para qué resultó especialmente útil la ADN polimerasa phi29 estudiada por Margarita Salas?", listOf("Para amplificar pequeñas cantidades de ADN", "Para producir rayos láser", "Para medir estrellas", "Para fabricar materiales resistentes"), 0),
    QuizQuestion("Biología", "¿Qué organismo utilizó Barbara McClintock principalmente para estudiar los elementos genéticos móviles?", listOf("Maíz", "Ratones", "Bacterias marinas", "Moscas"), 0),
    QuizQuestion("Biología", "¿Por qué los descubrimientos de Barbara McClintock fueron inicialmente recibidos con escepticismo?", listOf("Porque sus ideas sobre genes móviles eran muy adelantadas para la época", "Porque trabajaba exclusivamente con computadoras", "Porque no publicó ningún resultado", "Porque estudiaba astronomía"), 0),
    QuizQuestion("Biología", "Según la teoría desarrollada por Lynn Margulis, ¿cuál es el origen de las mitocondrias y los cloroplastos?", listOf("Antiguos virus", "Antiguas bacterias que establecieron una relación simbiótica", "Fragmentos de ADN humano", "Proteínas del núcleo"), 1),
    QuizQuestion("Biología", "¿Qué concepto defendió Lynn Margulis como mecanismo importante de evolución?", listOf("Simbiogénesis", "Radioactividad", "Relatividad", "Electromagnetismo"), 0),
    QuizQuestion("Biología", "¿Qué organismos estudió Nettie Stevens para investigar los cromosomas sexuales?", listOf("Escarabajos de la harina", "Delfines", "Plantas de maíz", "Bacterias oceánicas"), 0),
    QuizQuestion("Biología", "¿Qué demostraron las investigaciones de Nettie Stevens sobre los cromosomas X y Y?", listOf("Que participan en la determinación cromosómica del sexo", "Que producen energía celular", "Que controlan el envejecimiento", "Que generan anticuerpos"), 0),
    QuizQuestion("Biología", "¿Qué estructuras estudió Elizabeth Blackburn por su función de proteger los extremos de los cromosomas?", listOf("Ribosomas", "Telómeros", "Mitocondrias", "Centríolos"), 1),
    QuizQuestion("Biología", "¿Con quién codescubrió Elizabeth Blackburn la enzima telomerasa?", listOf("Carol Greider", "Marie Curie", "Lise Meitner", "Patricia Bath"), 0),
    QuizQuestion("Medicina", "¿Qué permite medir el radioinmunoensayo desarrollado por Rosalyn Yalow?", listOf("Sustancias presentes en cantidades extremadamente pequeñas en la sangre", "La distancia entre galaxias", "La resistencia de materiales", "El tamaño de los cromosomas"), 0),
    QuizQuestion("Medicina", "¿Qué decisión tomaron Rosalyn Yalow y Solomon Berson respecto al radioinmunoensayo?", listOf("Lo mantuvieron en secreto", "No patentaron la técnica", "Vendieron inmediatamente la patente", "Dejaron de utilizarlo"), 1),
    QuizQuestion("Medicina", "¿Qué sustancia estudió especialmente Flora de Pablo durante el desarrollo embrionario?", listOf("Proinsulina", "Kevlar", "Uranio", "Telomerasa"), 0),
    QuizQuestion("Medicina", "Además de su trabajo científico, ¿qué causa impulsó Flora de Pablo en España?", listOf("La igualdad de las mujeres en la ciencia", "La exploración espacial", "La fabricación de automóviles", "La enseñanza de astronomía infantil"), 0),
    QuizQuestion("Medicina", "¿Qué importancia histórica tuvo Cecilia Grierson en Argentina?", listOf("Fue una figura pionera de la medicina y la formación en enfermería", "Construyó el primer telescopio argentino", "Creó un lenguaje de programación", "Descubrió un nuevo elemento químico"), 0),
    QuizQuestion("Biología", "¿Qué relación tiene la investigación de Elizabeth Blackburn con problemas actuales de salud?", listOf("Ayuda a estudiar cáncer, envejecimiento y estabilidad genética", "Solo se utiliza para predecir el clima", "Permite fabricar materiales industriales", "Sirve únicamente para clasificar estrellas"), 0),
    QuizQuestion("Computación", "¿Por qué el nombre del experimento Fermi-Pasta-Ulam comenzó a modificarse para incluir a Mary Tsingou?", listOf("Porque ella realizó la programación computacional esencial del experimento", "Porque descubrió uno de los elementos utilizados", "Porque recibió el Premio Nobel por el experimento", "Porque dirigía la universidad donde se realizó"), 0)
)

val HardQuestionsList = listOf(
    QuizQuestion("Matemáticas", "¿Qué secuencia cronológica corresponde correctamente a Sophie Germain?", listOf("Correspondencia con Gauss → estudios secretos → premio de la Academia", "Estudios secretos → correspondencia con Gauss → premio de la Academia", "Premio de la Academia → correspondencia con Gauss → estudios secretos", "Estudios secretos → premio de la Academia → correspondencia con Gauss"), 1),
    QuizQuestion("Matemáticas", "¿Bajo qué seudónimo masculino estudió y se comunicó Sophie Germain?", listOf("M. LeBlanc", "M. Bernoulli", "M. Fourier", "M. Gauss"), 0),
    QuizQuestion("Matemáticas", "¿Qué científica obtuvo resultados relacionados con superficies de Riemann, espacios de módulos y trayectorias geodésicas?", listOf("Emmy Noether", "Maryam Mirzakhani", "Alice Chang", "Sofía Kovalevskaya"), 1),
    QuizQuestion("Matemáticas", "¿Cuál de estas características corresponde a Maryam Mirzakhani antes de su carrera universitaria?", listOf("Ganó dos medallas de oro en la Olimpiada Internacional de Matemática", "Trabajó en la NASA", "Estudió en el MIT desde niña", "Fue profesora en Oxford"), 0),
    QuizQuestion("Matemáticas", "¿Qué matemática trabajó especialmente con geometría conforme y ecuaciones diferenciales relacionadas con la curvatura?", listOf("Alice Chang", "Sophie Germain", "Ada Lovelace", "Emmy Noether"), 0),
    QuizQuestion("Matemáticas", "¿Qué reconocimiento recibió Alice Chang de la American Mathematical Society?", listOf("Premio Abel", "Premio Ruth Lyttle Satter", "Medalla Fields", "Premio Crafoord"), 1),
    QuizQuestion("Física", "Lise Meitner y Otto Frisch publicaron su explicación de la fisión nuclear en:", listOf("1918", "1925", "1939", "1966"), 2),
    QuizQuestion("Física", "¿Qué elemento químico lleva un nombre que homenajea a Lise Meitner?", listOf("Curio", "Meitnerio", "Fermio", "Lawrencio"), 1),
    QuizQuestion("Física", "¿Qué decisión relacionada con la Segunda Guerra Mundial se destaca en el perfil de Lise Meitner?", listOf("Se incorporó al Proyecto Manhattan", "Rechazó trabajar en el Proyecto Manhattan", "Dirigió el proyecto nuclear británico", "Abandonó definitivamente la física nuclear"), 1),
    QuizQuestion("Computación", "¿Cuál es el orden correcto en la trayectoria de Mary Tsingou?", listOf("MANIAC → Los Álamos → experimento FPUT", "Los Álamos → grupo MANIAC → experimento FPUT", "Experimento FPUT → MANIAC → Los Álamos", "Los Álamos → experimento FPUT → MANIAC"), 1),
    QuizQuestion("Computación", "¿En qué año comenzó a reconocerse de manera más explícita el nombre de Tsingou dentro del problema Fermi-Pasta-Ulam-Tsingou?", listOf("1955", "1972", "1998", "2008"), 3),
    QuizQuestion("Física", "¿Cuál de estas afirmaciones sobre Donna Strickland es correcta?", listOf("Su trabajo Nobel surgió de su tesis doctoral", "Recibió el Nobel antes de obtener el doctorado", "Desarrolló su técnica trabajando en NASA", "Fue la primera mujer de la historia en obtener un Nobel de Física"), 0),
    QuizQuestion("Física", "Donna Strickland compartió el Nobel de Física de 2018 con:", listOf("Gérard Mourou y Arthur Ashkin", "Otto Hahn y Fritz Strassmann", "Jack Szostak y Carol Greider", "Pierre Curie y Henri Becquerel"), 0),
    QuizQuestion("Física", "¿Qué obra publicó Helen Czerski en 2023 según su perfil?", listOf("The Blue Machine", "Ocean Physics", "Hidden Waves", "Bubble Theory"), 0),
    QuizQuestion("Física", "¿Qué reconocimiento recibió Helen Czerski en 2018?", listOf("Medalla Kelvin", "Medalla Copley", "Premio Faraday", "Medalla Franklin"), 0),
    QuizQuestion("Ingeniería", "¿En qué empresa realizó Stephanie Kwolek el trabajo que llevó al desarrollo del Kevlar?", listOf("General Electric", "DuPont", "Bell Labs", "IBM"), 1),
    QuizQuestion("Ingeniería", "¿Qué combinación de fechas corresponde a Stephanie Kwolek?", listOf("1946 ingreso a DuPont – 1965 descubrimiento clave – 1995 Hall of Fame", "1955 ingreso a DuPont – 1971 descubrimiento – 1990 Nobel", "1940 ingreso – 1952 patente – 1983 Nobel", "1965 ingreso – 1975 descubrimiento – 2001 Hall of Fame"), 0),
    QuizQuestion("Química", "¿Con qué artista estudió dibujo Marie-Anne Paulze-Lavoisier?", listOf("Claude Monet", "Jacques-Louis David", "Edgar Degas", "Auguste Rodin"), 1),
    QuizQuestion("Química", "¿Qué conocimiento lingüístico adquirió Marie-Anne Paulze-Lavoisier específicamente para apoyar su trabajo científico?", listOf("Alemán", "Italiano", "Inglés", "Ruso"), 2),
    QuizQuestion("Física", "Irène Joliot-Curie trabajó durante la Primera Guerra Mundial principalmente con:", listOf("Unidades móviles de rayos X", "Laboratorios de óptica", "Redes de telecomunicación", "Observatorios astronómicos"), 0),
    QuizQuestion("Física", "¿En qué año Irène Joliot-Curie y Frédéric Joliot-Curie anunciaron la radiactividad artificial?", listOf("1914", "1925", "1934", "1945"), 2),
    QuizQuestion("Biología", "¿Qué detalle diferencia el reconocimiento de Rosalind Franklin del de varias científicas laureadas de la lista?", listOf("Su reconocimiento principal fue ampliamente póstumo", "Recibió dos Nobel", "Recibió la Medalla Fields", "Nunca produjo publicaciones científicas"), 0),
    QuizQuestion("Biología", "La conocida Fotografía 51 fue tomada por:", listOf("Maurice Wilkins", "Raymond Gosling bajo la dirección de Franklin", "Francis Crick", "James Watson"), 1),
    QuizQuestion("Biología", "Además del ADN, Rosalind Franklin realizó estudios importantes sobre:", listOf("Virus", "Cometas", "Motores aeronáuticos", "Telómeros"), 0),
    QuizQuestion("Biología", "¿Con qué científico trabajó Margarita Salas entre 1964 y 1967 en Nueva York?", listOf("Santiago Ramón y Cajal", "Severo Ochoa", "Francis Crick", "Salvador Luria"), 1)
)
